export const collections = {
  accounts: "accounts",
  admins: "admins",
  adminMetrics: "adminMetrics",
  auditLogs: "auditLogs",
  budgets: "budgets",
  cardInstallments: "cardInstallments",
  cardInvoices: "cardInvoices",
  cardPayments: "cardPayments",
  cardPurchases: "cardPurchases",
  cards: "cards",
  categories: "categories",
  goals: "goals",
  globalCategories: "globalCategories",
  monthlySummaries: "monthlySummaries",
  recurringTransactions: "recurringTransactions",
  transactions: "transactions",
  users: "users",
} as const;

export const privateUserCollections = [
  collections.accounts,
  collections.categories,
  collections.transactions,
  collections.recurringTransactions,
  collections.monthlySummaries,
  collections.cards,
  collections.cardPurchases,
  collections.cardInstallments,
  collections.cardInvoices,
  collections.cardPayments,
  collections.budgets,
  collections.goals,
  "salaries",
  "balances",
  "expenses",
  "history",
  "cartoes",
  "orcamentos",
  "metas",
  "salarios",
  "saldos",
  "gastos",
  "historico",
] as const;
